name: Ferum Customizations CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server mariadb-client xvfb libxrender1 libxext6 libsm6
          sudo systemctl start redis-server

      - name: Install Bench CLI
        run: pip install frappe-bench

      - name: Set up Bench project
        run: |
          bench init test-bench --frappe-branch version-15 --python python3.11
          cd test-bench
          bench get-app ferum_customs ${{ github.workspace }}
          bench new-site test-site.local --mariadb-root-password root --admin-password admin --install-app erpnext
          bench --site test-site.local install-app ferum_customs

      - name: Run tests
        run: |
          cd test-bench
          bench --site test-site.local run-tests --app ferum_customs
